module.exports = [
  // https://github.com/Smoothieware/Smoothieware/blob/9e5477518b1c85498a68e81be894faea45d6edca/src/modules/utils/simpleshell/SimpleShell.cpp#L64
  'ls',
  'cd',
  'pwd',
  'cat',
  'echo',
  'rm',
  'mv',
  'mkdir',
  'upload',
  'reset',
  'dfu',
  'break',
  'help',
  'version',
  'mem',
  'get',
  'set_temp',
  'switch',
  'net',
  'load',
  'save',
  'remount',
  'calc_thermistor',
  'thermistors',
  'md5sum',
  'test',
  // [test] sub_commands
  'test jog',
  'test circle',
  'test square',
  'test raw',
  // [get] sub_commands
  'get temp',
  'get pos',
  'get wcs',
  'get state',
  'get status',
  'get fk',
  'get ik',
  // https://github.com/Smoothieware/Smoothieware/blob/9e5477518b1c85498a68e81be894faea45d6edca/src/modules/utils/simpleshell/SimpleShell.cpp#L273
  'config-get',
  'config-set',
  'config-load',
  'play',
  'progress',
  'abort',
  'suspend',
  'resume',
  'fire'
]
